"""empty message

Revision ID: 163a728f26b7
Revises: 5730e852ff98
Create Date: 2013-03-26 13:37:44.565709

"""

# revision identifiers, used by Alembic.
revision = '163a728f26b7'
down_revision = '5730e852ff98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_regex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('regex_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('screenshot', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regex_id')
    )
    op.add_column(u'regexes', sa.Column('name', sa.String(), nullable=True))
    op.add_column(u'regexes', sa.Column('title', sa.String(), nullable=True))
    op.add_column(u'regexes', sa.Column('text', sa.String(), nullable=True))
    op.add_column(u'regexes', sa.Column('meta', sa.String(), nullable=True))
    op.add_column(u'regexes', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column(u'regexes', sa.Column('type', sa.Enum(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'regexes', 'type')
    op.drop_column(u'regexes', 'date_added')
    op.drop_column(u'regexes', 'meta')
    op.drop_column(u'regexes', 'text')
    op.drop_column(u'regexes', 'title')
    op.drop_column(u'regexes', 'name')
    op.drop_table('user_regex')
    ### end Alembic commands ###
