"""empty message

Revision ID: 2ce75f6c657e
Revises: 163a728f26b7
Create Date: 2013-03-31 23:53:30.357070

"""

# revision identifiers, used by Alembic.
revision = '2ce75f6c657e'
down_revision = '163a728f26b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ScrapeHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('regex_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['regex_id'], ['regexes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ScrapeHistory')
    ### end Alembic commands ###
